ci: attempt to fix travis "too many open files" on macOS

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -45,6 +45,15 @@ script:
     (
       echo 'initial `cargo test` failed, retrying with fewer cores to work around OOM issues' &&
       cargo test --no-fail-fast --verbose -j 1
+    ) || (
+      # Travis has been consistently failing on macOS due to exhausting file descriptors
+      # which causes the file test suites to fail (keeping in mind that tokio-core is spinning
+      # up its own reactor file descriptor during each test which makes things worse).
+      # To get around this we'll try to run the test cases with just a single thread.
+      # FIXME(breaking): Once we've fully migrated off tokio-core and to tokio proper,
+      # this can go away
+      echo 'secondary `cargo test` failed, retrying with fewer cores and test threads' &&
+      cargo test --no-fail-fast --verbose -j 1 -- --test-threads 1
     )
 
 notifications:
